### ISSUE TITLE
L'Autre repos effacé

### ISSUE THREAD

**Issue by gaetan1903** [PetitPotiron/allreverso#1]
Je voulais savoir, il y avait un problème ? 

Pourquoi le repos a été effacé et transformer avec celui-ci ?

**Comment by PetitPotiron** [comment]
Bonjour, oui j'ai eu une erreur de manipulation, mais le code reste le même. Je vous ai donc mentionné pour que votre contribution soit quand même sur le repo actuel.

**Comment by gaetan1903** [comment]
D'accor, Merci
